#!/usr/bin/env python
# coding: utf-8

# Problem 2:
#   URL: http://projecteuler.net/problem=2
#   Subject: Even Fibonacci numbers
#     Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#     By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Problem 2:
#   URL: http://odz.sakura.ne.jp/projecteuler/index.php?cmd=read&page=Problem%202
#   Subject: 偶数のフィボナッチ数
#     フィボナッチ数列の項は前の2つの項の和である. 最初の2項を 1, 2 とすれば, 最初の10項は以下の通りである.
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#     数列の項の値が400万より小さい, 偶数値の項の総和を求めよ.
# 
#     Note:この問題は最近更新されました. お使いのパラメータが正しいかどうか確認してください.





